# Generated by Django 5.1.2 on 2024-10-15 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationuser',
            options={'verbose_name': 'Organization Admin', 'verbose_name_plural': 'Organization Admins'},
        ),
        migrations.AlterModelOptions(
            name='studentuser',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
