# Generated by Django 5.1.2 on 2024-10-15 13:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_question_quiz_question_organization_and_more'),
        ('users', '0002_alter_organizationuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correctanswer',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, to='dashboard.question'),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctsubmission', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentuser')),
            ],
        ),
    ]
